version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.5
    - 7.13.9
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.20.0
    - 7.21.0
  - dependency-name: tempy
    versions:
    - 1.0.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.7
